openapi: 3.1.0
info:
  version: 1.0.0
  title: NodeJS API Project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for a learning project managing users and contacts with authentication and email reset functionality.
tags:
  - name: Auth
  - name: Contacts
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-u8gt.onrender.com
paths:
  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/id/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/id/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/id/delete.yaml'
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Contact:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
          required: true
        phoneNumber:
          type: string
          required: true
        email:
          type: string
        isFavourite:
          type: boolean
          default: false
        contactType:
          type: string
          enum: ['work', 'home', 'personal']
          default: 'personal'
          required: true
        photo:
          type: string
          default: null
        userId:
          type: string
          required: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - name
        - phoneNumber
        - contactType
        - userId
