openapi: 3.1.0
info:
  version: 1.0.0
  title: NodeJS API Project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for a learning project managing users and contacts with authentication and email reset functionality.
tags:
  - name: Auth
  - name: Contacts
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-u8gt.onrender.com
paths:
  /contacts/{contactId}:
    get:
      $ref: './swagger/paths/contacts/{id}/get.yaml'
  /contacts:
    get:
      $ref: './swagger/paths/contacts/get.yaml'
  /contacts/{contactId}:
    patch:
      $ref: './swagger/paths/contacts/{id}/patch.yaml'
  /contacts/{contactId}:
    delete:
      $ref: './swagger/paths/contacts/{id}/delete.yaml'
  /contacts:
    post:
      $ref: './swagger/paths/contacts/post.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
